# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-31 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglist',
            name='form_thankyou',
            field=tinymce.models.HTMLField(blank=True, default=b'', verbose_name='Success message'),
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='form_title',
            field=models.CharField(blank=True, default=b'', max_length=255, verbose_name='form title'),
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='message_subject',
            field=models.CharField(blank=True, default=b'', max_length=255, verbose_name='Message subject'),
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='message_template',
            field=models.TextField(blank=True, default=b'', verbose_name='Message template'),
        ),
        migrations.AlterField(
            model_name='mailinglist',
            name='form',
            field=models.CharField(max_length=100, unique=True, verbose_name='form'),
        ),
    ]
