# Generated by Django 2.2.28 on 2024-08-27 04:31

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20190731_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglist',
            name='form_thankyou',
            field=tinymce.models.HTMLField(blank=True, default='', verbose_name='Success message'),
        ),
        migrations.AlterField(
            model_name='mailinglist',
            name='form_title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='form title'),
        ),
        migrations.AlterField(
            model_name='mailinglist',
            name='message_subject',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Message subject'),
        ),
        migrations.AlterField(
            model_name='mailinglist',
            name='message_template',
            field=models.TextField(blank=True, default='', verbose_name='Message template'),
        ),
    ]
